theme: minima
title: Your awesome title
author: Andrea Pandulis
email: a.pandulis@unibit.bg
description: > # this means to ignore newlines until "baseurl:"
  One of the greatest joys known to man is to take a flight into ignorance in search of knowledge. 
                                                                            Robert Staughton Lynd

# social links
twitter_username: AndreaPandulis
github_username:  Pandulis

show_excerpts: true # set to false to remove excerpts on the homepage
